### ISSUE TITLE
De kaarten worden ,in het begin bij het uitdelen, niet geprint

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#2]

**Comment by osmanseker** [comment]
![image](https://user-images.githubusercontent.com/50238194/104129742-cfeeb380-536d-11eb-945a-e73dc4f82aa1.png)
de kaarten worden inderdaad niet geprint.

![image](https://user-images.githubusercontent.com/50238194/104129754-e09f2980-536d-11eb-812d-b76bb9788599.png)
om dit op te lossen heb ik de print functie op het einde erbij gezet. nu werkt het wel.
![image](https://user-images.githubusercontent.com/50238194/104129763-ed238200-536d-11eb-95b8-5acf33cd34f5.png)
