### ISSUE TITLE
Ik kan een  'infinite' lange naam schrijven

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#3]

**Comment by osmanseker** [comment]
Ik heb het getest en het kan inderdaad
![image](https://user-images.githubusercontent.com/50238194/104129803-21973e00-536e-11eb-8327-a03b1f6e7db3.png)

door dit toe te passen kan je maar max 10 letters schrijven als naam
![image](https://user-images.githubusercontent.com/50238194/104129821-3b388580-536e-11eb-8f8e-ffa2aa75ba98.png)
