### ISSUE TITLE
Bij de totale score wordt de naam van de speler niet geprint

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#4]

**Comment by osmanseker** [comment]
![image](https://user-images.githubusercontent.com/50238194/104129837-50151900-536e-11eb-949a-9b661110a0d3.png)

Dit heb ik opgelost door het toevoegen van de naam. Dit was ik vergeten erbij te zetten.
![image](https://user-images.githubusercontent.com/50238194/104129848-5f946200-536e-11eb-84ac-0542c74b3202.png)
nu werkt het wel
![image](https://user-images.githubusercontent.com/50238194/104129856-64591600-536e-11eb-9ad7-37583c1cd530.png)
