### ISSUE TITLE
Er komen rare tekens bij het optellen van de totale scores

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#5]

**Comment by osmanseker** [comment]
![image](https://user-images.githubusercontent.com/50238194/104129877-76d34f80-536e-11eb-9728-6f37f4f9e291.png)
dit had was eerder niet het probleem bij mij

![image](https://user-images.githubusercontent.com/50238194/104129894-85ba0200-536e-11eb-8e30-5ba0d4dae10f.png)
ik heb later dit stukje code toegepast om rekening te houden met de memory maar zo te zien doet het programma er dan moeilijk over. ik heb de unsigned __int8 terug vervangen door gewoon een int en nu werkt het wel
![image](https://user-images.githubusercontent.com/50238194/104129960-aeda9280-536e-11eb-9844-ea5a417388d2.png)
