### ISSUE TITLE
Er staat meteen Game over na het optellen van de totale scores

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#6]

**Comment by osmanseker** [comment]
![image](https://user-images.githubusercontent.com/50238194/104129992-bdc14500-536e-11eb-9a08-cb420d22cbf6.png)

dit heb ik opgelost door de "check()" fucntie weg te halen. Deze moet op die plek nog niet opgeroepen worden.
![image](https://user-images.githubusercontent.com/50238194/104130019-d598c900-536e-11eb-90b1-51b860fc25c9.png)
Nu komt er niet meer meteen "game over" te staan
