### ISSUE TITLE
De totale score van de dealer klopt nooit

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#7]

**Comment by osmanseker** [comment]
![image](https://user-images.githubusercontent.com/50238194/104130082-0da00c00-536f-11eb-863b-2e50cf82a5af.png)
Dit heb ik over het hoofd gezien

Ik heb het opgelost door de scores in de .h files in het begin op 0 te zetten.
![image](https://user-images.githubusercontent.com/50238194/104130095-26a8bd00-536f-11eb-9cf8-2b1a64f2a820.png)

nu klopt het wel
![image](https://user-images.githubusercontent.com/50238194/104130100-2e686180-536f-11eb-8925-bc381085a6d8.png)
