### ISSUE TITLE
Als ik kies voor Hit wordt de kaart niet geprint

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#8]

**Comment by osmanseker** [comment]
![image](https://user-images.githubusercontent.com/50238194/104130121-522ba780-536f-11eb-8164-ebe3eb103aff.png)

Ik heb een printfucntie toegevoegd bij de toebehoorde kaart en nu is deze bug gefixt.
![image](https://user-images.githubusercontent.com/50238194/104130194-b8b0c580-536f-11eb-80ec-382de8042d91.png)
![image](https://user-images.githubusercontent.com/50238194/104130122-55269800-536f-11eb-8f86-29bd6cd575a8.png)
