### ISSUE TITLE
Als ik Hit kies met hoofdletter H dan gebeurt er niets

### ISSUE THREAD

**Issue by RasitAkay11** [osmanseker/Blackjack-Cpp#9]

**Comment by osmanseker** [comment]
Ik wist niet dat dit een issue zou zijn
![image](https://user-images.githubusercontent.com/50238194/104130132-6a9bc200-536f-11eb-96b5-3d00d27b980f.png)

Ik heb deze bug gefixt door onderstaande code toe te passen
![image](https://user-images.githubusercontent.com/50238194/104130138-75eeed80-536f-11eb-93aa-013290568806.png)
Nu werkt het zowel als hoofdletter als kleine letters
![image](https://user-images.githubusercontent.com/50238194/104130166-91f28f00-536f-11eb-851f-16d0f631e739.png)
